var properties = [
{status: 'not for sale', name:'GO', priceGain:200},

{owned: false,
  owner: null,
  name:'Bag End',
  underscore: 'Bag_End',
  initials: 'B. E.',
  color: 'brown',
   cost: 60,
   rent:2,
   monopolyRent: 4,
   house1:10,
   house2:30,
   house3:90,
   house4:160,
   hotel:250,
   mortgage:30,
   houseCost:50,
   hotelCost:50
}, 

{status: 'not for sale', name:'Smaug\'s Treasure'},

{owned: false,
  owner: null,
  name:'Farmer Maggot\'s',
  underscore: 'Farmer_Maggot\'s',
  initials: 'F. M.',
  color: 'brown',
   cost:60,
   rent:4,
   monopolyRent: 8,
   house1:20,
   house2:60,
   house3:180,
   house4:320,
   hotel:450,
   mortgage:30,
   houseCost:50,
   hotelCost:50},

{status: 'not for sale', name:'Seen By The Palantir',
    cost1:'10%',
    cost2:200},

{owned: false,
  owner: null,
  name:'Bill the Pony',
  underscore: 'Bill_the_Pony',
  initials: 'B. T. P.',
  color: 'black',
   cost:200,
   rent:25,
   railroadrent2:50,
   monopolyRent:100,
   railroadrent4:200,
   mortgage:100
   },

{owned: false,
  owner: null,
  name:'Buckleberry Ferry',
  underscore: 'Buckleberry_Ferry',
  initials: 'B. F.',
  color: 'bluegray',
   cost: 100,
   rent:6,
   monopolyRent: 12,
   house1:30,
   house2:90,
   house3:270,
   house4:400,
   hotel:550,
   mortgage:50,
   houseCost:50,
   hotelCost:50},

{status: 'not for sale', name:'Landroval'},

{owned: false,
  owner: null,
  name:'Bree',
  underscore: 'Bree',
  initials: 'B.',
  color: 'bluegray',
   cost:100,
   rent:6,
   monopolyRent: 12,
   house1:30,
   house2:90,
   house3:270,
   house4:400,
   hotel:550,
   mortgage:50,
   houseCost:50,
   hotelCost:50},

{owned: false,
  owner: null,
  name:'Weathertop',
  underscore: 'Weathertop',
  initials: 'W.',
  color: 'bluegray',
   cost:120,
   rent:8,
   monopolyRent:16,
   house1:40,
   house2:100,
   house3:300,
   house4:450,
   hotel:600,
   mortgage:60,
   houseCost:50,
   hotelCost:50},

{status: 'not for sale', name:'Dol Guldur'},

{owned: false,
  owner: null,
  name:'Ford of Bruinen',
  underscore: 'Ford_of_Bruinen',
  initials: 'F. O. B.',
  color: 'violet',
   cost:140,
   rent:10,
   monopolyRent:20,
   house1:50,
   house2:150,
   house3:450,
   house4:625,
   hotel:750,
   mortgage:70,
   houseCost:100,
   hotelCost:100},

{owned: false,
  owner: null,
  name:'Staff of Gandalf',
  underscore: 'Staff_of_Gandalf',
  initials: 'S. O. G.',
  color: 'white',
  cost: 150,
   utilities1:'(4x diceroll)',
   utilities2:'(10x diceroll)'
   },

{owned: false,
  owner: null,
  name:'Rivendell',
  underscore: 'Rivendell',
  initials: 'R.',
  color: 'violet',
   cost:140,
   rent:10,
   monopolyRent: 20,
   house1:50,
   house2:150,
   house3:450,
   house4:625,
   hotel:750,
   mortgage:70,
   houseCost:100,
   hotelCost:100},

{owned: false,
  owner: null,
  name:'Caradhras',
  underscore: 'Caradhras',
  initials: 'C.',
  color: 'violet',
   cost:160,
   rent:12,
   monopolyRent: 24,
   house1:60,
   house2:180,
   house3:500,
   house4:700,
   hotel:900,
   mortgage:80,
   houseCost:100,
   hotelCost:100},

{owned: false,
  owner: null,
  name:'Brego',
  underscore: 'Brego',
  initials: 'B.',
  color: 'black',
   cost:200,
   rent:25,
   railroadrent2:50,
   monopolyRent:100,
   railroadrent4:200,
   mortgage:100},

{owned: false,
  owner: null,
  name:'Mines of Moria',
  underscore: 'Mines_of_Moria',
  initials: 'M. O. M.',
  color: 'orange',
   cost:180,
   rent:14,
   monopolyRent: 28,
   house1:70,
   house2:200,
   house3:550,
   house4:750,
   hotel:950,
   mortgage:90,
   houseCost:100,
   hotelCost:100},

{status: 'not for sale', name:'Smaug\'s Treasure'},

{owned: false,
  owner: null,
  name:'Lothlorien',
  underscore: 'Lothlorien',
  initials: 'L.',
  color: 'orange',
   cost:180,
   rent:14,
   monopolyRent: 28,
   house1:70,
   house2:200,
   house3:550,
   house4:750,
   hotel:950,
   mortgage:90,
   houseCost:100,
   hotelCost:100},

{owned: false,
  owner: null,
  name:'Falls of Rauros',
  underscore: 'Falls_of_Rauros',
  initials: 'F. O. R.',
  color: 'orange',
   cost:200,
   rent:16,
   monopolyRent: 32,
   house1:80,
   house2:220,
   house3:600,
   house4:800,
   hotel:1000,
   mortgage:100,
   houseCost:100,
   hotelCost:100},

{status: 'not for sale', name:'free parking'},

{owned: false,
  owner: null,
  name: 'Gap of Rohan',
  underscore: 'Gap_of_Rohan',
  initials: 'G. O. R.',
  color: 'red',
       cost: 220,
       rent:18,
       monopolyRent:36,
       house1:90,
       house2:250,
       house3:700,
       house4:875,
       hotel:1050,
       houseCost:150,
       hotelCost:150,
       mortage:110
        },

{status: 'not for sale', name:'Landroval'},

{owned: false,
  owner: null,
  name: 'Helm\'s Deep',
  underscore: 'Helm\'s_Deep',
  initials: 'H. D.',
  color: 'red',
        cost:220,
        rent:18,
        monopolyRent:36,
        house1:90,
        house2:250,
        house3:700,
        house4:875,
        hotel:1050,
        houseCost:150,
        hotelCost:150,
        mortage:110},

{owned: false,
  owner: null,
  name:'Edoras',
  underscore: 'Edoras',
  initials: 'E.',
  color: 'red',
      cost:240,
       rent:20,
       monopolyRent:40,
        house1:100,
        house2:300,
        house3:750,
        house4:925,
        hotel:1100,
        houseCost:150,
        hotelCost:150},

{owned: false,
  owner: null,
  name:'Asfaloth',
  underscore: 'Asfaloth',
  initials: 'A.',
       cost:200,
       color: 'black',
       rent:25,
       railroadrent2:50,
       monopolyRent:100,
       railroadrent4:200,
       mortgage:100
        },

{owned: false,
  owner: null,
  name:'Fangorn Forest',
  underscore: 'Fangorn_Forest',
  initials: 'F. F.',
  color: 'yellow',
       cost:300,
        rent:22,
        monopolyRent:44,
        house1:110,
        house2: 330,
        house3:800,
        house4:975,
        hotel:1150,
        houseCost:150,
        hotelCost:150,
        mortgage:130},

{owned: false,
  owner: null,
  name:'Westfold',
  underscore: 'Westfold',
  initials: 'W.',
  color: 'yellow',
        cost:260,
        rent:22,
        monopolyRent:44,
        house1:110,
        house2:330,
        house3:800,
        house4:975,
        hotel:1150,
        houseCost:150,
        hotelCost:150,
        mortgage:130},

{owned: false,
  owner: null,
  name:'Staff of Saruman',
  underscore: 'Staff_of_Saruman',
  initials: 'S. O. S.',
  color: 'white',
       cost:150,
       utilities1:'(4x diceroll)',
       utilities2:'(10x diceroll)'
},

{owned: false,
  owner: null,
  name:'Isengard',
  underscore: 'Isengard',
  initials: 'I.',
  color: 'yellow',
      cost:280,
      rent:24,
       monopolyRent:48,
       house1:120,
       house2:360,
       house3:850,
       house4:1025,
       hotel:1200,
       houseCost:150,
       hotelCost:150,
       mortgage:140
       },

{status: 'not for sale', name:'Dul Guldur'},

{owned: false,
  owner: null,
  name:'Osgiliath',
  underscore: 'Osgiliath',
  initials: 'O.',
  color: 'green',
       cost:300,
        rent:26,
        monopolyRent:52,
        house1:130,
        house2: 390,
        house3: 900,
        house4: 1100,
        hotel:12075,
        houseCost:200,
        hotelCost:200,
        mortgage:150
       },

{owned: false,
  owner: null,
  name:'Pelennor Fields',
  underscore: 'Pelennor_Fields',
  initials: 'P. F.',
  color: 'green',
      cost:300,        
       rent:26,
       monopolyRent:52,
       house1:130,
       house2:390,
       house3:900,
       house4:1100,
       hotel:12075,
       houseCost:200,
      hotelCost:200,
      mortgage:150
       },

{status: 'not for sale', name:'Smaug\'s Treasure'},

{owned: false,
  owner: null,
  name: 'Minas Tirith',
  underscore: 'Minas_Tirith',
  initials: 'M. T.',
  color: 'green',
      cost:320,
      rent: 28,
      monopolyRent:56,
      house1:150,
       house2:450,
       house3:1000,
       house4:1200,
       hotel:1400,
       houseCost:200,
       hotelCost:200,
       mortgage:160
       },

{owned: false,
  owner: null,
  name:'Shadowfax',
  underscore: 'Shadowfax',
  initials: 'S.',
  color: 'black',
       cost:200,
       rent:25,
       railroadrent2:50,
       monopolyRent:100,
       reailroadrent4:200
      },

{status: 'not for sale', name:'Landroval'},

{owned: false,
  owner: null,
  name:'Barad Dur',
  underscore: 'Barad_Dur',
  initials: 'B. D.',
  color: 'blue',
       cost:350,
       rent:35,
       monopolyRent:70,
       house1:175,
       house2:500,
       house3:1100,
       house4:1300,
       hotel:1500,
       houseCost:200,
       hotelCost:200,
       mortgage:175
       },

{name:'Shelob\'s Lair',
      rent:100},

{owned: false,
  owner: null,
  name:'Mt. Doom',
  underscore: 'Mt._Doom',
  initials: 'M. D.',
  color: 'blue',
      cost:400,
      rent:50,
      monopolyRent:100,
      house1:200,
      house2:600,
      house3:1400,
      house4:1700,
      hotel:2000,
      houseCost:200,
      hotelCost:200,
      mortgage:200
       }
]